# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/lab-central-webapp',
                'doc_host': 'https://corradin-lab.github.io',
                'git_url': 'https://github.com/corradin-lab/lab-central-webapp',
                'lib_path': 'src/lab_central_webapp'},
  'syms': { 'lab_central_webapp.core': {'lab_central_webapp.core.foo': ('core.html#foo', 'lab_central_webapp/core.py')},
            'lab_central_webapp.pipeline_registry': {},
            'lab_central_webapp.settings': {}}}
